// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jellyfin.Plugin.CollectionImageGenerator.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CollectionImageGenerationFeature : object, global::Xunit.IClassFixture<CollectionImageGenerationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Collection Image Generation", "    As a Jellyfin server administrator\n    I want collections without images to h" +
                "ave collages auto-generated\n    So that my library has a polished appearance", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CollectionImageGeneration.feature"
#line hidden
        
        public CollectionImageGenerationFeature(CollectionImageGenerationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/CollectionImageGeneration.feature", "Feature: Collection Image Generation\n    As a Jellyfin server administrator\n    I" +
                    " want collections without images to have collages auto-generated\n    So that my " +
                    "library has a polished appearance\n\n    Scenario: Grid dimensions adapt to item c" +
                    "ount of 1\n        Given a collection has 1 item with images\n        Then the gri" +
                    "d dimensions should be 1 row and 1 column\n\n    Scenario: Grid dimensions adapt t" +
                    "o item count of 2\n        Given a collection has 2 items with images\n        The" +
                    "n the grid dimensions should be 1 row and 2 columns\n\n    Scenario: Grid dimensio" +
                    "ns adapt to item count of 3\n        Given a collection has 3 items with images\n " +
                    "       Then the grid dimensions should be 1 row and 3 columns\n\n    Scenario: Gri" +
                    "d dimensions adapt to item count of 4\n        Given a collection has 4 items wit" +
                    "h images\n        Then the grid dimensions should be 2 rows and 2 columns\n\n    Sc" +
                    "enario: Collage positions match image count\n        Given a collection has 5 ite" +
                    "ms with images\n        Then the collage layout should contain 5 positions\n\n    S" +
                    "cenario: Large collections cap at 9 grid positions\n        Given a collection ha" +
                    "s 12 items with images\n        Then the collage layout should contain 9 position" +
                    "s\n\n    Scenario: Default configuration enables scheduled task\n        Given the " +
                    "default plugin configuration\n        Then the scheduled task should be enabled\n\n" +
                    "    Scenario: Default configuration sets max images to 4\n        Given the defau" +
                    "lt plugin configuration\n        Then the max images in collage should be 4\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/CollectionImageGeneration.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Collection Image Generation", "    As a Jellyfin server administrator\n    I want collections without images to h" +
                        "ave collages auto-generated\n    So that my library has a polished appearance", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Grid dimensions adapt to item count of 1", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 1 item with images", null, null, "c64d6de6410b7e568b73169a7818ed88"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the grid dimensions should be 1 row and 1 column", null, null, "ab9cebb1372e07549af84a48b3d3477e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "8c3884896462ed57a600ee3b1644defc")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Grid dimensions adapt to item count of 2", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 2 items with images", null, null, "ad97c3eb5860835d9540359d5b9660f7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the grid dimensions should be 1 row and 2 columns", null, null, "a8068b51356f835280b75ac53419e583")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0360b6a9cd8e305ca4c71ec1d79e2977")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Grid dimensions adapt to item count of 3", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 3 items with images", null, null, "19ba5857b5915553ac134676cf7acb53"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the grid dimensions should be 1 row and 3 columns", null, null, "0fd58d7bc7b26e579583badaff8395b7")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e7c01266e034bf5bac873e6532f9897b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Grid dimensions adapt to item count of 4", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 4 items with images", null, null, "9a1480abeb9a7a5d8186a6bf4132ab63"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the grid dimensions should be 2 rows and 2 columns", null, null, "eeb26336dcd57655974d0918b9a556ad")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "008a2b409530f25d8fb192a37cde2a8f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Collage positions match image count", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 5 items with images", null, null, "9b7e2e842b08cd579513c9dab433cb99"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collage layout should contain 5 positions", null, null, "b491103ea831a0539ac4d0e56b9b487b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "c14ba1f5d9c62f5ebb9668c79b14f678")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Large collections cap at 9 grid positions", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a collection has 12 items with images", null, null, "1457de1456a6895ebf92b2f424a4c236"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the collage layout should contain 9 positions", null, null, "a9d74c8b40783d509ca148b92ccb923f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2bb4eaeef563365da13b9bbc6544816b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Default configuration enables scheduled task", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the default plugin configuration", null, null, "8e7f8911412adc579e453e880f1681d1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the scheduled task should be enabled", null, null, "2601af13199a7b529fce21445004bf2d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "85b2937e55d52e549d98477defb838bc")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Default configuration sets max images to 4", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the default plugin configuration", null, null, "d29b08e95d7ce456a8e7af178bd3ba98"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the max images in collage should be 4", null, null, "7d3aed20fa679259b8ef8509010d198b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f605169c0b41ab5f904eb0007e5c1c84"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("f5f44e0ea907e159a2cf28f126e8b5e9", "Features/CollectionImageGeneration.feature", "Grid dimensions adapt to item count of 1", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c64d6de6410b7e568b73169a7818ed88"}), "ecd7b345c5dbfb55ba3cf6d272babf95", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 1 item with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab9cebb1372e07549af84a48b3d3477e"}), "67043dc923d5b95688ca45029bad4692", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the grid dimensions should be 1 row and 1 column")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "8c3884896462ed57a600ee3b1644defc"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("faec991fe5051959bd733048bce87d15", "Features/CollectionImageGeneration.feature", "Grid dimensions adapt to item count of 2", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ad97c3eb5860835d9540359d5b9660f7"}), "f25dcb6b0be3075f9c414b0e5e24d742", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 2 items with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a8068b51356f835280b75ac53419e583"}), "f4b399872aa7fb5abf2706dd6ede853e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the grid dimensions should be 1 row and 2 columns")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0360b6a9cd8e305ca4c71ec1d79e2977"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f902aaf77e8dba5f93081516fef159ee", "Features/CollectionImageGeneration.feature", "Grid dimensions adapt to item count of 3", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "19ba5857b5915553ac134676cf7acb53"}), "a03aea513aeafc56968a01e86d23d7e7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 3 items with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0fd58d7bc7b26e579583badaff8395b7"}), "1bb3f7cfa68878559a17918299ec917c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the grid dimensions should be 1 row and 3 columns")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e7c01266e034bf5bac873e6532f9897b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("129e6c1601063559b14e01625506dcb7", "Features/CollectionImageGeneration.feature", "Grid dimensions adapt to item count of 4", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9a1480abeb9a7a5d8186a6bf4132ab63"}), "3df896dfb752195ebd6fd44bb978801a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 4 items with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eeb26336dcd57655974d0918b9a556ad"}), "b288ca4887996c51ae3cc386f1adecaf", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the grid dimensions should be 2 rows and 2 columns")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "008a2b409530f25d8fb192a37cde2a8f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("25b514ebe2effd5c92afa99341f2bf53", "Features/CollectionImageGeneration.feature", "Collage positions match image count", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9b7e2e842b08cd579513c9dab433cb99"}), "7a9f3e2f2996c859bbea57ef6dcc59c8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 5 items with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b491103ea831a0539ac4d0e56b9b487b"}), "a9c8eed3d41d9b53b850d2fb3e92571e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collage layout should contain 5 positions")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "c14ba1f5d9c62f5ebb9668c79b14f678"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e6327a397a20b45db9c47953f36bb2a8", "Features/CollectionImageGeneration.feature", "Large collections cap at 9 grid positions", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1457de1456a6895ebf92b2f424a4c236"}), "134d5a2d3c7a655eb3b60578f531dda9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a collection has 12 items with images"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a9d74c8b40783d509ca148b92ccb923f"}), "73d636372e3c1b54a406d44c2dcfe03e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the collage layout should contain 9 positions")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "2bb4eaeef563365da13b9bbc6544816b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("584fcc776cc9665e8b836801bb68a8f5", "Features/CollectionImageGeneration.feature", "Default configuration enables scheduled task", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8e7f8911412adc579e453e880f1681d1"}), "62e2e7f490ad7757ba10b3ae5d0bc309", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the default plugin configuration"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2601af13199a7b529fce21445004bf2d"}), "c07ce1afc7f9a5529e2b9980b19fe9d8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the scheduled task should be enabled")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "85b2937e55d52e549d98477defb838bc"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("57ba2f250e4a185e80a61873da51286a", "Features/CollectionImageGeneration.feature", "Default configuration sets max images to 4", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d29b08e95d7ce456a8e7af178bd3ba98"}), "16f54be46a38835cb65fbeb83a21c8a0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the default plugin configuration"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7d3aed20fa679259b8ef8509010d198b"}), "a7ce73640e61865a989f743f9e11e045", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the max images in collage should be 4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "f605169c0b41ab5f904eb0007e5c1c84"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(CollectionImageGenerationFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(CollectionImageGenerationFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(CollectionImageGenerationFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Grid dimensions adapt to item count of 1")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Grid dimensions adapt to item count of 1")]
        public async global::System.Threading.Tasks.Task GridDimensionsAdaptToItemCountOf1()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Grid dimensions adapt to item count of 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await testRunner.GivenAsync("a collection has 1 item with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
        await testRunner.ThenAsync("the grid dimensions should be 1 row and 1 column", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Grid dimensions adapt to item count of 2")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Grid dimensions adapt to item count of 2")]
        public async global::System.Threading.Tasks.Task GridDimensionsAdaptToItemCountOf2()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Grid dimensions adapt to item count of 2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
        await testRunner.GivenAsync("a collection has 2 items with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
        await testRunner.ThenAsync("the grid dimensions should be 1 row and 2 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Grid dimensions adapt to item count of 3")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Grid dimensions adapt to item count of 3")]
        public async global::System.Threading.Tasks.Task GridDimensionsAdaptToItemCountOf3()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Grid dimensions adapt to item count of 3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
        await testRunner.GivenAsync("a collection has 3 items with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
        await testRunner.ThenAsync("the grid dimensions should be 1 row and 3 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Grid dimensions adapt to item count of 4")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Grid dimensions adapt to item count of 4")]
        public async global::System.Threading.Tasks.Task GridDimensionsAdaptToItemCountOf4()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Grid dimensions adapt to item count of 4", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
        await testRunner.GivenAsync("a collection has 4 items with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
        await testRunner.ThenAsync("the grid dimensions should be 2 rows and 2 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Collage positions match image count")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Collage positions match image count")]
        public async global::System.Threading.Tasks.Task CollagePositionsMatchImageCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Collage positions match image count", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
        await testRunner.GivenAsync("a collection has 5 items with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
        await testRunner.ThenAsync("the collage layout should contain 5 positions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Large collections cap at 9 grid positions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Large collections cap at 9 grid positions")]
        public async global::System.Threading.Tasks.Task LargeCollectionsCapAt9GridPositions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Large collections cap at 9 grid positions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
        await testRunner.GivenAsync("a collection has 12 items with images", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
        await testRunner.ThenAsync("the collage layout should contain 9 positions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Default configuration enables scheduled task")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Default configuration enables scheduled task")]
        public async global::System.Threading.Tasks.Task DefaultConfigurationEnablesScheduledTask()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Default configuration enables scheduled task", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
        await testRunner.GivenAsync("the default plugin configuration", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
        await testRunner.ThenAsync("the scheduled task should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Default configuration sets max images to 4")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Collection Image Generation")]
        [global::Xunit.TraitAttribute("Description", "Default configuration sets max images to 4")]
        public async global::System.Threading.Tasks.Task DefaultConfigurationSetsMaxImagesTo4()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Default configuration sets max images to 4", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
        await testRunner.GivenAsync("the default plugin configuration", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
        await testRunner.ThenAsync("the max images in collage should be 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CollectionImageGenerationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CollectionImageGenerationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
